<?php
// $Id$

/**
 * Implements hook_uninstall().
 */
function menu_block_uninstall() {
  foreach (variable_get('menu_block_enabled_blocks', array()) AS $delta => $enabled) {
    variable_del("menu_block_{$delta}_mid");
    variable_del("menu_block_{$delta}_level");
    variable_del("menu_block_{$delta}_depth");
    variable_del("menu_block_{$delta}_expanded");
  }
  variable_del('menu_block_enabled_blocks');
}
